import numpy
import pytest
from tracts.phase_type.hybrid_pedigree import hybrid_pedigree_distribution
from test_data import bins, Ls
from tracts.legacy.demographic_model import DemographicModel
from tracts.phase_type.base_phase_type import PhaseTypeDistribution
from tracts.phase_type.monoecious import PhTMonoecious
from tracts.phase_type.dioecious import PhTDioecious

"""
This test suite contains tests for the core functionality of the Phase-Type Distribution implementation, including tests for the correctness of the transition matrices,
equilibrium distributions, and tract length histograms generated by the Phase-Type Distribution models under various migration scenarios. The tests also include comparisons
between the Phase-Type Distribution results and those obtained from the demographic_model implementation to ensure consistency between the two approaches. 
Additionally, there are tests for the computation of t0_proportions under unbiased and biased migration scenarios, as well as tests for the hybrid pedigree distribution function.
The test suite is designed to validate the core components of the Phase-Type Distribution implementation and ensure that they are functioning correctly across a range of scenarios.
"""

# ----------------- Migration matrices for testing -----------------

@pytest.fixture
def migration_matrix_A():
    return numpy.array([[0, 0], [0, 0], [0.1, 0], [0, 0], [0, 0], [0, 0], [0.2, 0.8]])

@pytest.fixture
def migration_matrix_B():
    return numpy.array([[0, 0], [0, 0], [0, 0.5], [0.6, 0.4]])

@pytest.fixture
def migration_matrix_C():
    return numpy.array([[0, 0], [0, 0], [0, 0.5], [0.2, 0.2], [0.6, 0.4]])

@pytest.fixture
def migration_matrix_D():
    return numpy.array([[0, 0], [0, 0], [0, 0.3], [1, 0]])

@pytest.fixture
def migration_matrix_E():
    return numpy.array([[0, 0], [0, 0], [0.7, 0.3]])

@pytest.mark.parametrize("data", ["migration_matrix_A", "migration_matrix_B",
                                  "migration_matrix_C", "migration_matrix_D"])

# ----------------- Testing functions -----------------


def test_PDT_Monoecious(data, request):
    """
    Checks that the Monoecious Phase-Type model generates valid transition matrices and equilibrium distributions.
    """
    migration_matrix = request.getfixturevalue(data)
    PTD = PhTMonoecious(migration_matrix)

    # Verify that the equilibrium distribution is a valid probability vector
    assert min(PTD.equilibrium_distribution) >= 0
    assert numpy.isclose(numpy.linalg.norm(PTD.equilibrium_distribution, ord=1), 1)

    # Verify that the determinant of the transition matrix is 0
    assert numpy.isclose(numpy.linalg.det(PTD.full_transition_matrix), 0)
    assert numpy.allclose(numpy.dot(PTD.equilibrium_distribution, PTD.full_transition_matrix), 0)


def verify_similar_ptd_models(ptd_first: PhaseTypeDistribution, ptd_second: PhaseTypeDistribution,
                              atol: float = 0.02):
    """
    A function to verify that two Phase-Type Distribution models produce similar tract length distributions under the same migration scenario. 
    This is used to compare different Phase-Type models that behave similarly when sex-bias and difference in sex-specific recombination rates is not strong.
    """

    # ----------------- Phase-Type densities -----------------

    newbins, counts_first, E = ptd_first.tractlength_histogram_windowed(population_number=0,
                                                                        bins=bins, L=Ls[1],
                                                                        density=True,
                                                                        freq=False)
    newbins, counts_second, E = ptd_second.tractlength_histogram_windowed(population_number=0,
                                                                        bins=bins,
                                                                        L=Ls[1],
                                                                        density=True,
                                                                        freq=False)
    
    # ----------------- Phase-Type densities in frequency scale -----------------

    newbins, counts_first_freq, E = ptd_first.tractlength_histogram_windowed(population_number=0,
                                                                            bins=bins,
                                                                            L=Ls[1],
                                                                            density=True,
                                                                            freq=True)
    newbins, counts_second_freq, E = ptd_second.tractlength_histogram_windowed(population_number=0,
                                                                            bins=bins,
                                                                            L=Ls[1],
                                                                            density=True,
                                                                            freq=True)
    
    # ----------------- Phase-Type histograms in count scale -----------------

    outbins, counts_first_hist, E = ptd_first.tractlength_histogram_windowed(population_number=0,
                                                                            bins=bins,
                                                                            L=Ls[1],
                                                                            density=False)
    outbins, counts_second_hist, E = ptd_second.tractlength_histogram_windowed(population_number=0,
                                                                            bins=bins,
                                                                            L=Ls[1],
                                                                            density=False)

    # Densities must be close
    assert numpy.all(numpy.isclose(counts_first, counts_second, atol=atol))
    # And the frequencies
    assert numpy.all(numpy.isclose(counts_first_freq, counts_second_freq, atol=atol))
    # And the histograms
    assert numpy.all(numpy.isclose(counts_first_hist, counts_second_hist, atol=atol))


def verify_same_t0_proportions_unbiased(ptd_autosome: PhaseTypeDistribution,
                              ptd_X: PhaseTypeDistribution, atol: float = 0.02):
    
    """
    Checks that the ancestry proportions at generation t=0 are the same for autosomal and X chromosome admixture under unbiased migration.
    """
    
    if ptd_autosome.X_chr or not ptd_X.X_chr:
        raise Exception("The first and second models need to be autosomal and allosomal, respectively.")
    if not numpy.all(numpy.isclose(ptd_autosome.migration_matrix_f, ptd_autosome.migration_matrix_m, atol=atol)):
        raise Exception("The sex-specific migration matrices of the autosomal model must be the same for this comparison.")
    if not numpy.all(numpy.isclose(ptd_X.migration_matrix_f, ptd_X.migration_matrix_m, atol=atol)):
        raise Exception("The sex-specific migration matrices of the autosomal model must be the same for this comparison.")
    if not numpy.all(numpy.isclose(ptd_autosome.migration_matrix_f, ptd_X.migration_matrix_f, atol=atol)):
        raise Exception("The sex-specific migration matrices of both models must be the same for this comparison.")
    if not numpy.all(numpy.isclose(ptd_autosome.migration_matrix_m, ptd_X.migration_matrix_m, atol=atol)):
        raise Exception("The sex-specific migration matrices of both models must be the same for this comparison.")

    # Check that t0_proportions are the same for autosomal and X chromosome admixture under unbiased migration.
    assert numpy.all(numpy.isclose(ptd_autosome.t0_proportions_f, ptd_autosome.t0_proportions_m, atol=atol))
    assert numpy.all(numpy.isclose(ptd_X.t0_proportions_f, ptd_X.t0_proportions_m, atol=atol))
    assert numpy.all(numpy.isclose(ptd_autosome.t0_proportions_f, ptd_X.t0_proportions_m, atol=atol))

def verify_autosomal_t0_recursive(ptd_autosome: PhaseTypeDistribution, atol: float = 0.02):
    """
    Checks that the ancestry proportions at generation t=0 for the autosomal model can be computed recursively and match the direct computation.
    This is a consistency check for the computation of t0_proportions in autosomes, which should be the same whether computed directly or recursively,
    and serves as a validation of the implementation of the recursive computation of ancestry proportions in allosomes.
    """

    if ptd_autosome.X_chr:
        raise Exception("The model needs to be autosomal for this test.")

    # Compute the autosomal t0_proportions recursively, analogously as the X chromosome case.
    migration_matrix_f = ptd_autosome.migration_matrix_f_unchanged # Get migration matrices
    migration_matrix_m = ptd_autosome.migration_matrix_m_unchanged
    num_generations = migration_matrix_f.shape[0]

    ancestry_proportions_m = migration_matrix_m[num_generations - 1, ]
    ancestry_proportions_f = migration_matrix_f[num_generations - 1, ]
    for generation_number in range(num_generations - 2, 0, -1):
               
        ancestry_proportions_f_prev = ancestry_proportions_f.copy()
        ancestry_proportions_m_prev = ancestry_proportions_m.copy()
        ancestry_proportions_m = migration_matrix_m[generation_number, ] + (1 - migration_matrix_m[generation_number, ].sum())*(ancestry_proportions_m_prev + ancestry_proportions_f_prev)/2 
        ancestry_proportions_f = migration_matrix_f[generation_number, ] + (1 - migration_matrix_f[generation_number, ].sum())*(ancestry_proportions_m_prev + ancestry_proportions_f_prev)/2           
            
    t0_proportions_f = ancestry_proportions_f
    t0_proportions_m = ancestry_proportions_m

    # Compare the t0_proportions computed recursively with the ones computed directly.
    assert numpy.all(numpy.isclose(ptd_autosome.t0_proportions_f, t0_proportions_f, atol=atol))
    assert numpy.all(numpy.isclose(ptd_autosome.t0_proportions_m, t0_proportions_m, atol=atol))



def verify_ptd_dioecious_matrices(pht: PhTDioecious):
    """
    Checks that the transition matrices of the Dioecious model are valid, meaning that they have non-negative entries and that the rows sum to 0, which is a requirement for continuous-time Markov chains.
    """
    assert numpy.all(numpy.isclose(numpy.sum(pht.full_transition_matrix_f, axis=1), 0))
    assert numpy.all(numpy.isclose(numpy.sum(pht.full_transition_matrix_m, axis=1), 0))

@pytest.mark.parametrize("data", ["migration_matrix_A", "migration_matrix_B",
                                  "migration_matrix_C", "migration_matrix_D"])

def test_PDT_Dioecious(data, request):
    """
    Checks that Phase-Type distributions are close between the Monoecious and Dioecious models under unbiased migration and equal sex-specific recombination rates.
    Checks also that the transition matrices of the Dioecious model are valid.
    """
    migration_matrix = request.getfixturevalue(data)
    
    PTD_Monoecious = PhTMonoecious(migration_matrix=migration_matrix)

    PTD_Dioecious_F = PhTDioecious(migration_matrix_f=migration_matrix,
                                migration_matrix_m=migration_matrix,
                                rho_f=1,
                                rho_m=1,
                                sex_model='DF')
    
    PTD_Dioecious_C = PhTDioecious(migration_matrix_f=migration_matrix,
                                migration_matrix_m=migration_matrix,
                                rho_f=1,
                                rho_m=1,
                                sex_model='DC')
    
    verify_similar_ptd_models(ptd_first=PTD_Monoecious,
                              ptd_second=PTD_Dioecious_F)
    
    verify_similar_ptd_models(ptd_first=PTD_Monoecious,
                              ptd_second=PTD_Dioecious_C)
    
    verify_ptd_dioecious_matrices(PTD_Dioecious_F)
    verify_ptd_dioecious_matrices(PTD_Dioecious_C)


@pytest.mark.parametrize("data", ["migration_matrix_A", "migration_matrix_B",
                                  "migration_matrix_C", "migration_matrix_D"])

def test_t0_proportions(data, request):
    """
    Checks that the ancestry proportions at generation t=0 are computed correctly for both autosomal and X chromosome admixture under unbiased migration.
    Also checks that the recursive computation of t0_proportions for the autosomal model matches the direct computation.
    """
    migration_matrix = request.getfixturevalue(data)
    
    PTD_Dioecious_aut = PhTDioecious(migration_matrix_f=migration_matrix,
                                    migration_matrix_m=migration_matrix,
                                    rho_f=1,
                                    rho_m=1,
                                    sex_model='DC',
                                    X_chromosome=False)
    
    PTD_Dioecious_X = PhTDioecious(migration_matrix_f=migration_matrix,
                                migration_matrix_m=migration_matrix,
                                rho_f=1,
                                rho_m=1,
                                sex_model='DC',
                                X_chromosome = True,
                                X_chromosome_male = False)
    
    # For unbiased migration matrices
    verify_same_t0_proportions_unbiased(PTD_Dioecious_aut, PTD_Dioecious_X)
    verify_autosomal_t0_recursive(PTD_Dioecious_aut) 
    
    # For biased migration rates
    prop_of_female_migration = 0.8 # 0.5 for unbiased migration, 1 for only female migrants, 0 for only male migrants.
    mig_m = 2*migration_matrix*(1-prop_of_female_migration)
    mig_f = 2*migration_matrix*prop_of_female_migration
    mig_m[-1,:] = migration_matrix[-1,:]
    mig_f[-1,:] = migration_matrix[-1,:]
    
    PTD_Dioecious_aut_biased = PhTDioecious(migration_matrix_f=mig_f,
                                            migration_matrix_m=mig_m,
                                            rho_f=1, 
                                            rho_m=1,
                                            sex_model='DC',
                                            X_chromosome=False)
    
    verify_autosomal_t0_recursive(PTD_Dioecious_aut_biased)


@pytest.mark.parametrize("data", ["migration_matrix_A", "migration_matrix_B",
                                  "migration_matrix_C", "migration_matrix_D"])

def test_PDT_X(data, request):
    """
    Checks that Phase-Type distributions are close between the Monoecious and Dioecious models under unbiased migration and equal sex-specific recombination rates for X chromosome admixture, and that the transition matrices of the Dioecious model are valid.
    """
    migration_matrix = request.getfixturevalue(data)
    for Xcmale in [True, False]:

        PTD_Dioecious_F = PhTDioecious(migration_matrix_f=migration_matrix,
                                    migration_matrix_m=migration_matrix,
                                    rho_f=1,
                                    rho_m=1,
                                    sex_model='DF',
                                    X_chromosome=True,
                                    X_chromosome_male=Xcmale)
        
        PTD_Dioecious_C = PhTDioecious(migration_matrix_f=migration_matrix,
                                    migration_matrix_m=migration_matrix,
                                    rho_f=1,
                                    rho_m=1,
                                    sex_model='DC',
                                    X_chromosome=True,
                                    X_chromosome_male=Xcmale)
        
        verify_similar_ptd_models(ptd_first=PTD_Dioecious_F,
                                ptd_second=PTD_Dioecious_C, atol=0.15)

        # Basic checks for X-chromosome models
        verify_ptd_dioecious_matrices(PTD_Dioecious_F)
        verify_ptd_dioecious_matrices(PTD_Dioecious_C)


@pytest.mark.parametrize("data", ["migration_matrix_A", "migration_matrix_B",
                                  "migration_matrix_C", "migration_matrix_D"])

def test_pedigree(data, request):
    """
    Checks that the hybrid-pedigree models can be ran under various migration scenarios and that they produce valid tract length distributions.
    """
    # Hybrid pedigree model with TP = 2
    migration_matrix = request.getfixturevalue(data)

    # --------------- Phase-type mixture densities ---------------

    result_bins, counts_HP_aut = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=False,
                                                            X_chr_male=False,
                                                            N_cores=5,
                                                            density=True,
                                                            freq=False)
    
    result_bins, counts_HP_X = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=True,
                                                            X_chr_male=False,
                                                            N_cores=5,
                                                            density=True,
                                                            freq=False)
    
    result_bins, counts_HP_Xm = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2, L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=True,
                                                            X_chr_male=True,
                                                            N_cores=5,
                                                            density=True,
                                                            freq=False)

    assert numpy.all(counts_HP_aut >= 0)
    assert numpy.all(counts_HP_X >= 0)
    assert numpy.all(counts_HP_Xm >= 0)

    # --------------- Phase-type mixture densities in frequency scale ---------------

    result_bins, counts_HP_aut = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=False,
                                                            X_chr_male=False,
                                                            N_cores=5,
                                                            density=True,
                                                            freq=True)
    
    result_bins, counts_HP_X = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=True,
                                                            X_chr_male=False,
                                                            N_cores=5,
                                                            density=True,
                                                            freq=True)
    
    result_bins, counts_HP_Xm = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=True,
                                                            X_chr_male=True,
                                                            N_cores=5,
                                                            density=True,
                                                            freq=True)

    assert numpy.all(counts_HP_aut >= 0)
    assert numpy.all(counts_HP_X >= 0)
    assert numpy.all(counts_HP_Xm >= 0)

    # --------------- Phase-type mixture histograms in count scale ---------------

    result_bins, counts_HP_aut = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=False,
                                                            X_chr_male=False,
                                                            N_cores=5,
                                                            density=False,
                                                            freq=False)
    
    result_bins, counts_HP_X = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2, L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=True,
                                                            X_chr_male=False,
                                                            N_cores=5,
                                                            density=False,
                                                            freq=False)
    
    result_bins, counts_HP_Xm = hybrid_pedigree_distribution(mig_matrix_f=migration_matrix,
                                                            mig_matrix_m=migration_matrix,
                                                            TP=2,
                                                            L=Ls[1],
                                                            bingrid=bins,
                                                            whichpop=0,
                                                            rho_f=1,
                                                            rho_m=1,
                                                            X_chr=True,
                                                            X_chr_male=True,
                                                            N_cores=5,
                                                            density=False,
                                                            freq=False)

    assert numpy.all(counts_HP_aut >= 0)
    assert numpy.all(counts_HP_X >= 0)
    assert numpy.all(counts_HP_Xm >= 0)


def compare_normalization_factors(migration_matrix, Ls, population_number):
    """
    Checks that the normalization factor Z computed by the Monoecious Phase-Type model matches the Z computed by the DemographicModel for a
    range of chromosome lengths, and that the expected number of tracts per bin from the DemographicModel matches
    the expected number of tracts per bin from the Phase-Type distribution when scaled by Z.
    """

    PTD = PhTMonoecious(migration_matrix)
    demo = DemographicModel(migration_matrix)
    tracts_z = demo.Z(Ls, population_number)
    phase_type_z = numpy.array([PTD.normalization_factor([L], PTD.transition_matrices[population_number],
                                                         PTD.inverse_S0_list[population_number],
                                                         PTD.alpha_list[population_number]) for L in Ls])
    print(f'Z from DemographicModel: {tracts_z}')
    print(f'Z from Monoecious Phase-Type model: {phase_type_z}')
    assert numpy.allclose(tracts_z, phase_type_z)

def verify_PDT(migration_matrix):
    """
    Compares the tract length histograms generated by the Monoecious Phase-Type model and the DemographicModel for a given migration matrix, and checks that they are similar.
    """
    print(f'Migration Matrix:\n{migration_matrix}')

    models = ModelComparison(migration_matrix)
    models.compare_models(bins, Ls[0], 0)
    models.compare_proportions()
    models.compare_TpopTau()
    compare_normalization_factors(migration_matrix, [1], 1)

@pytest.mark.parametrize("data", ["migration_matrix_A", "migration_matrix_B",
                                  "migration_matrix_C", "migration_matrix_D"])

def test_verify_PDT(data, request):
    """
    Implements the verify_PDT testing suite. 
    """
    migration_matrix = request.getfixturevalue(data)
    verify_PDT(migration_matrix)


class ModelComparison:
    """
    A class for comparing tract length distributions generated with the Monoecious Phase-Type implementation (tracts 2.0) and the DemographicModel implementation (tracts 1.0) under the same unbiased setting.
    Both implementations should produce similar result if no sex-biased migration or recombination is present.
    """

    def __init__(self, migration_matrix):
        """
        Initializes the ModelComparison class by creating instances of the Monoecious Phase-Type model and the DemographicModel using the provided migration matrix. 
        """
        self.migration_matrix = migration_matrix
        self.PTD = PhTMonoecious(migration_matrix)
        self.demo = DemographicModel(migration_matrix)

    def compare_proportions(self):
        """
        Checks that the ancestry proportions at generation t=0 are the same for the Monoecious Phase-Type model and the DemographicModel under unbiased migration.
        """
        print(f'DemographicModel proportions at t0: {self.demo.proportions[0]}')
        print(f'Monoecious Phase-Type proportions at t0: {self.PTD.t0_proportions}')
        assert numpy.allclose(self.demo.proportions[0], self.PTD.t0_proportions, atol=0.01)

    def compare_TpopTau(self):
        """
        Checks that the TpopTau values computed by the Monoecious Phase-Type model match those computed by the DemographicModel for all population pairs and generations.
        """
        for tpopTau, result in self.demo.dicTpopTau.items():
            assert self.PTD._get_TpopTau(tpopTau[0], tpopTau[1], tpopTau[2]) == result
        print('TpopTau is equal for Monoecious Phase-Type and DemographicModel. All assertions passed.')

    def compare_models(self, bins, L, population_number):
        """
        Checks that the tract length histograms generated by the Monoecious Phase-Type model and the DemographicModel are similar.
        """
        PTD_hist_tuple = self.PTD.tractlength_histogram_windowed(population_number, bins, L)
        PTD_hist = PTD_hist_tuple[1]
        demo_hist = self.demo.expectperbin([L], population_number, bins)[:-1]
        print(f'\nTractlength histogram from Monoecious Phase-Type: \n{PTD_hist}')
        print(f'\nTractlength histogram from DemographicModel: \n{numpy.array(demo_hist)}')
        assert numpy.allclose(PTD_hist, numpy.array(demo_hist), atol=0.01)

   





