import matplotlib.pyplot as plt
import numpy
import scipy
from tracts.legacy.demographic_model import DemographicModel
from tracts.phase_type.monoecious import PhTMonoecious
from tests.test_data import bins

def plot_histogram_model_comparison(PTD_hist: numpy.ndarray, demo_hist: numpy.ndarray, L: float):
    """
    Plots a comparison between the tract length distribution generated by the Monoecious Phase-Type model and the expected number of tracts per bin generated by the DemographicModel for a given chromosome length.
    This function creates a log-log plot of the expected number of tracts per bin for both models, as well as a plot of the ratio of the two distributions. It also calculates and displays the slope of the ratio and the Pearson correlation coefficient between the two distributions.

    Parameters
    ----------
    PTD_hist : array-like
        The tract length distribution generated by the Monoecious Phase-Type model.
    demo_hist : array-like
        The expected number of tracts per bin generated by the DemographicModel.
    L : float
        The length of the chromosome for which to compare the tract length distributions.
    """

    print(sum(PTD_hist))
    print(sum(demo_hist))
    fig, ax = plt.subplots(1, 2)
    L = round(L, 3)
    ax[0].loglog(bins, demo_hist, label='DemographicModel')
    ax[0].loglog(bins, PTD_hist, label='Monoecious Phase-Type')
    ax[0].set_title(f"Log-Log Plot of Expected Number of Tracts Per Bin\n on a chromosome of length {L}")
    ax[0].set_xlabel("Bin Value")
    ax[0].set_ylabel("Expected number of tracts")
    ax[1].plot(demo_hist, PTD_hist)
    ax[1].set_title(
        f"Ratio of Monoecious Phase-Type Distribution tracts to DemographicModel tracts\n On a chromosome of length {L}")
    ax[1].set_xlabel("DemographicModel")
    ax[1].set_ylabel("Monoecious Phase-Type")
    ratio = round(sum(demo_hist) / sum(PTD_hist), 3)
    Rstat = scipy.stats.pearsonr(PTD_hist, demo_hist)
    ax[1].text(0.05, 0.95,
               f'Slope: {ratio} \nR-value: {round(Rstat.statistic, 3)} \nP-Value: {round(Rstat.pvalue, 3)}',
               transform=ax[1].transAxes, fontsize=14,
               verticalalignment='top')
    plt.show()

class ModelComparison:
    """
    A class for comparing tract length distributions generated with the Monoecious Phase-Type implementation (tracts 2.0) and the DemographicModel implementation (tracts 1.0) under the same unbiased setting.
    Both implementations should produce similar result if no sex-biased migration or recombination is present.
    """

    def __init__(self, migration_matrix: numpy.ndarray):
        """
        Initializes the ModelComparison class by creating instances of the Monoecious Phase-Type model and the DemographicModel using the provided migration matrix. 
        """
        self.migration_matrix = migration_matrix
        self.PTD = PhTMonoecious(migration_matrix)
        self.demo = DemographicModel(migration_matrix)
  
    def per_bin_noscale(self, demographic_model: DemographicModel, input_bins: list, L: float, population_number: int):
        """
        Computes the expected number of tracts per bin using the PDF of the tract length distribution from the DemographicModel, without scaling by the normalization factor Z.
        """
        PDF = lambda x: (demographic_model.inners(L, x, population_number) +
                     demographic_model.outers(L, x, population_number)) / demographic_model.Z(L, population_number)
        binval = lambda binNum: scipy.integrate.quad(PDF, input_bins[binNum], input_bins[binNum + 1])
        lsval = [binval(binNum)[0] for binNum in range(len(input_bins) - 1)]
        lsval.append(demographic_model.full(L, population_number) / demographic_model.Z(L, population_number))
        return numpy.array(lsval)

    def compare_models(self, input_bins: list, L: float, population_number: int):
        """
        Compares the tract length distributions generated by the Monoecious Phase-Type model and the DemographicModel for a given population number, chromosome length, and set of bins.
        This function computes the expected number of tracts per bin for both models and plots them on a log-log plot, as well as plotting the ratio of the two distributions. It also calculates and displays
        the slope of the ratio and the Pearson correlation coefficient between the two distributions.

        Parameters
        ----------
        input_bins : list
            A list of bin edges for computing the expected number of tracts per bin.
        L : float
            The length of the chromosome for which to compare the tract length distributions.
        population_number : int
            The population number for which to compare the tract length distributions.
        """

        PTD_hist_tuple = self.PTD.tractlength_histogram_windowed(population_number=population_number,
                                                                bins=bins,
                                                                L=L)
        PTD_hist = PTD_hist_tuple[1]
        demo_hist = self.demo.expectperbin(Ls=[L],
                                           pop=population_number,
                                           bins=input_bins)
        
        plot_histogram_model_comparison(PTD_hist=PTD_hist,
                                        demo_hist=demo_hist,
                                        L=L)

    # -------------------------------------------------------------------------------------------------------------------------------------
    #TODO: Verify the usefulness of the following functions. Note that they involve some quantites called weird_factors. 
    # This should probably be removed. Note that correspondence between tracts 1.0 and tracts 2.0 is already verified in test_phase_type.py.

    def compare_models_4(self, bins, L, population_number):
        """
        Compares the tract length distributions generated by the Monoecious Phase-Type model and the DemographicModel for a given population number, chromosome length, and set of bins, without scaling by the normalization factor Z.
        """
        PTD_hist_tuple = self.PTD.tractlength_histogram_windowed(population_number, bins, L)
        PTD_hist = PTD_hist_tuple[1]
        demo_hist = self.per_bin_noscale(self.demo, bins, L, population_number)[:-1]
        try:
            assert len(PTD_hist) == len(demo_hist)  # == len(demo_hist2)
        except AssertionError:
            print("Lengths of PTD_hist and demo_hist do not match.")
            return
        
        print(f'Chromosome has length {L}.')
        print(f'Normalized tractlength distribution from DemographicModel using bin midpoints:\n{demo_hist}')
        print(f'Normalized tractlength distribution from Monoecious PhaseType model:\n{PTD_hist}')

    def compare_models_5(self, bins, Ls, population_number):
        # TODO: Discuss if this can be automatically verified
        print(f'Chromosome lengths:\n {Ls}')
        Z = numpy.array([self.PTD.normalization_factor([L], self.PTD.transition_matrices[population_number],
                                                       self.PTD.inverse_S0_list[population_number],
                                                       self.PTD.alpha_list[population_number]) for L in Ls])

        ratios = numpy.array([numpy.sum(self.demo.expectperbin([L], population_number, bins)) / numpy.sum(
            self.PTD.tractlength_histogram_windowed(population_number, bins, L)[1]) for L in Ls])
        print(f'\nRatios of expectperbin (tracts) to histogram (PhaseType): \n{ratios}')
        print(f'\nRatios divided by Z: \n{numpy.divide(ratios, Z)}')
        weird_factors = self.weird_factors(Ls, population_number)
        print(f'\nScaling factor from tracts: \n{weird_factors} ')
        print(f'\nScaling factor over Z: \n{numpy.divide(weird_factors, Z)}')

    def compare_models_6(self, population_number, Ls):
        # TODO: Discuss if this can be automatically verified
        # TODO: This function wasn't even in the comments
        # print(f'Alpha * S0_inverse:\n {self.alpha_s0_inv(population_number)} ')
        print(f'Chromosome lengths: \n{numpy.array(Ls)}')
        print(f'\nScaling factor from tracts: \n{self.weird_factors(Ls, population_number)} ')
        Z_to_tracts_factor = 2 * self.PTD.t0_proportions[population_number] / self.alpha_s0_inv(population_number)
        Z = numpy.array([self.PTD.normalization_factor([L], self.PTD.transition_matrices[population_number],
                                                       self.PTD.inverse_S0_list[population_number],
                                                       self.PTD.alpha_list[population_number]) for L in Ls])
        print(f'\n  Z * 2 * (proportions at t0) / (alpha*s0_inverse) * -1: \n{-Z * Z_to_tracts_factor}')
        print(f'\nTracts self.totSwitchDensity:\n {self.demo.totSwitchDens[population_number]}')
        print(f'\n2 * (proportions at t0) / (alpha*s0_inverse) * -1: \n{-Z_to_tracts_factor}')
        return

    def alpha_s0_inv(self, population_number):
        """
        The product of alpha and S0_inv for the given population
        """
        # TODO: The function is only present in the comments, discuss if it should be removed
        return numpy.dot(self.PTD.alpha_list[population_number], self.PTD.inverse_S0_list[population_number])

    def weird_factors(self, Ls, population_number):
        return numpy.array(
            [L * self.demo.totSwitchDens[population_number] + 2. * self.demo.proportions[0, population_number] for L in
             Ls])
    
    