import itertools
import warnings
from abc import ABC, abstractmethod
import logging 
import numpy as np
from numpy.exceptions import ComplexWarning
import numpy.typing as npt
import scipy
from scipy import integrate
from scipy.special import gammaln
logger = logging.getLogger(__name__)

# -------- Helper function --------

def get_survival_factors(migration_matrix):
    r"""
    Takes a migration matrix of :math:`T` generations and returns a list of length :math:`T`,
    which is the probability of a migrant allele from that generation surviving to the present.
    Valid only under the monoecious model, that is, assuming unbiased migration and recombination rates for autosomal admixture.

    Parameters
    ----------
    migration_matrix: npt.ArrayLike
        A :math:`T\times P` array, where :math:`T` is the number of generations, and :math:`P` is the number of populations.
    
    Returns
    -------
    npt.ArrayLike
        A vector of length :math:`T`, where the entry at index :math:`t` is the probability of a migrant allele from generation :math:`t` surviving to the present.
    """
    survival_factors = np.ones(len(migration_matrix))
    for generation_number in range(1, len(migration_matrix)):
        survival_factors[generation_number] = survival_factors[generation_number - 1] * (
                1 - sum(migration_matrix[generation_number - 1]))
    return survival_factors

# -------- Phase-Type class --------

class PhaseTypeDistribution(ABC):
    """
    A class representing the phase-type distribution of tract lengths
    generated by a given (pair of) migration matrix (matrices).

    Attributes
    ----------
    maxLen: float
        The maximum tract length considered in the distribution. Used to speed up computations by ignoring tracts longer than maxLen, which are very unlikely to be observed in real data. If None, considers tracts of all lengths.
    num_populations: int
        The number of populations in the model, inferred from the migration matrix.
    migration_matrix: npt.ArrayLike
        The migration matrix defining the demographic model. Used only under monoecious admixture.
    migration_matrix_f: npt.ArrayLike
        The migration matrix describing migration of female individuals, used only under dioecious admixture.
    migration_matrix_m: npt.ArrayLike
        The migration matrix describing migration of male individuals, used only under dioecious admixture.
    t0_proportions: npt.ArrayLike
        The proportions of tracts that originate from each population at time `t=0`. Computed using Eq. (F-27) in the manuscript.
    t0_proportions_f: npt.ArrayLike
        The proportions of maternally-inherited tracts that originate from each population at time `t=0`. For autosomes,
        computed using Eq. (F-27) in the manuscript. For the X chromosome, computing using the recursive equations (F-28) and (F-29) in the manuscript.
    t0_proportions_m: npt.ArrayLike
        The proportions of paternally-inherited tracts that originate from each population at time `t=0`. For autosomes,
        computed using Eq. (F-27) in the manuscript. For the X chromosome, computing using the recursive equations (F-28) and (F-29) in the manuscript.
    transition_matrices: list of npt.ArrayLike
        A list of the transition matrices for tracts originating from each population, used only under monoecious admixture.
    transition_matrices_f: list of npt.ArrayLike
        A list of the transition matrices for maternally-inherited tracts, used only under dioecious admixture.
    transition_matrices_m: list of npt.ArrayLike
        A list of the transition matrices for paternally-inherited tracts, used only under dioecious admixture.
    S0_list: list of npt.ArrayLike
        A list containing the sum across columns of every transition matrix in `transition_matrices`.
    S0_list_f: list of npt.ArrayLike
        A list containing the sum across columns of every transition matrix in `transition_matrices_f`.
    S0_list_m: list of npt.ArrayLike
        A list containing the sum across columns of every transition matrix in `transition_matrices_m`.
    inverse_S0_list: list of npt.ArrayLike
        A list containing the sum across columns of the inverse of every transition matrix in `transition_matrices`, used only under monoecious admixture.
    inverse_S0_list_f: list of npt.ArrayLike
        A list containing the sum across columns of the inverse of every transition matrix in `transition_matrices_f`, used only under dioecious admixture.
    inverse_S0_list_m: list of npt.ArrayLike
        A list containing the sum across columns of the inverse of every transition matrix in `transition_matrices_m`, used only under dioecious admixture.
    alpha_list: list of npt.ArrayLike
        A list of the initial probability vectors for tracts originating from each population, used only under monoecious admixture.
    alpha_list_f: list of npt.ArrayLike
        A list of the initial probability vectors for maternally-inherited tracts, used only under dioecious admixture.
    alpha_list_m: list of npt.ArrayLike
        A list of the initial probability vectors for paternally-inherited tracts, used only under dioecious admixture.
    X_chr: bool
        Whether the tract length distribution is for tracts on the X chromosome.
    X_chr_male: bool
        Whether the tract length distribution is for tracts on the X chromosome in male individuals.

    Notes
    -----
    Non-listed attributes are for internal use only.
    """

    def __init__(self):
        """
        Initialize the PhaseTypeDistribution object.
        """

        self.maxLen = None
        self.num_populations = None
        self.migration_matrix = None
        self.migration_matrix_f = None
        self.migration_matrix_m = None
        self.t0_proportions = None
        self.t0_proportions_f = None
        self.t0_proportions_m = None
        self.S0_list = None
        self.S0_list_f = None
        self.S0_list_m = None
        self.inverse_S0_list = None
        self.inverse_S0_list_m = None
        self.inverse_S0_list_f = None
        self.alpha_list = None
        self.alpha_list_m = None
        self.alpha_list_f = None
        self.transition_matrices = None
        self.transition_matrices_f = None
        self.transition_matrices_m = None
        self.prop_at_1 = None
        self.m_prop_at_2 = None
        self.m_prop_at_1 = None
        self.f_prop_at_2 = None
        self.f_prop_at_1 = None       
        self.X_chr = None
        self.X_chr_male = None        
    
    @abstractmethod
    def PhT_density(self, x, population_number, s1=None):
        pass

    @abstractmethod
    def PhT_density_windowed(self, population_number, S, alpha, S0_inv, bins: npt.ArrayLike, L: float, s1=None,
                             exp_Sx_per_bin: npt.ArrayLike = None):
        pass

    @staticmethod
    def initialize_density_bins(bins: npt.ArrayLike, L: float, alpha: float, S0_inv: float):
        r"""
        Initialize the density bins for the phase-type distribution. Performs initial checks, truncates the bins to the finite chromosome length, and computes the expected tract length under the finite chromosome model.
        
        Parameters
        ----------
        bins: npt.ArrayLike
            A point grid on :math:`(0, \infty)` where the density have to be evaluated.
        L: float
            The chromosome length.
        alpha: npt.ArrayLike
            The initial probability vector for the Phase-type process.
        S0_inv: npt.ArrayLike
            The sum across columns of the inverse of the transition submatrix.
        
        Returns
        -------
        npt.ArrayLike
            The sorted and truncated bins on :math:`(0, L)` where the density will be evaluated.
        float
            The expected tract length under the finite chromosome model.
        float
            The normalization factor :math:`Z` for the density under the finite chromosome model.
        """

        bins = np.asarray(bins)
        if ~np.any(np.isin(bins, L)): # Add L to the bins vector if not already present
            bins = np.append(bins, L)
        
        bins = bins[bins <= L] # Truncate to [0, L], where the distribution is supported
        bins = np.sort(bins)
        E_val = -np.dot(alpha, S0_inv) # Expectation under the infinite chromosome model
        if not np.isreal(E_val) or E_val <= -1e-3:
            raise Exception('Expectation is not a positive real : ', E_val)
        ET = float(np.real(E_val).item())
        Z = ET + L # Normalization factor
        ETL = L * ET / Z # Expectation under the finite chromosome model
        return bins, ETL, Z

    def populate_density_bins(self, bins: npt.ArrayLike, population_number: int, ETL: float,
                              prop_connected: float, prop_isolated: float, exp_Sx_per_bin: npt.ArrayLike,
                              L: float, Z: float, s1: float | None, alpha: npt.ArrayLike, S: npt.ArrayLike, S0_inv: npt.ArrayLike):
        r"""
        Populate the density values for the phase-type distribution on the given bins, under the finite chromosome model. 

        Parameters
        ----------
        bins: npt.ArrayLike
            A point grid on :math:`(0, L)` where the density have to be evaluated.
        population_number: int
            The population of interest whose tract length distribution has to be computed.
        ETL: float
            The expected tract length under the finite chromosome model.
        prop_connected: float
            The probability of a tract to being drawn from the Phase-type process with connected state space.
        prop_isolated: float
            The probability of a tract being drawn from the Phase-type process with an isolated single state.
        exp_Sx_per_bin: npt.ArrayLike
            A list of the precomputed values of :math:`e^{\mathbf{S}x}` for every bin, where :math:`\mathbf{S}` is the transition matrix for the Phase-type process.
        L: float
            The chromosome length.
        Z: float
            The normalization factor for the density under the finite chromosome model.
        s1: float | None
            The sex of the individual at generation 1. If `s1 = 0` (resp. 1), only alleles
            paternally (resp. maternally) inherited alleles are considered. If set to None,
            tracts on both copies are combined.
        alpha: npt.ArrayLike
            The initial probability vector for the Phase-type process.
        S: npt.ArrayLike
            The transition matrix for the Phase-type process.
        S0_inv: npt.ArrayLike
            The sum across column of the inverse matrix of :math:`\mathbf{S}`.

        Returns
        -------
        npt.ArrayLike
            The sorted and truncated bins on :math:`(0, L)` where the density will be evaluated.
        npt.ArrayLike
            The density values for the phase-type distribution on the given bins, under the finite chromosome model.
        float
            The expected tract length under the finite chromosome model.
        """

        bin_start_index = 0
        if bins[0]>0: # If first bin is nonzero, add zero bin just to check sum rules. 
            bin_start_index = 1 
            extend_bins = np.zeros(len(bins)+1)
            extend_bins[1:] = bins
            bins = extend_bins 
        
        ETL = prop_connected * ETL + prop_isolated * L
        if not np.isclose(prop_isolated + prop_connected, 1):
            raise Exception('Probabilities of initial hyper-states do not sum up to one.')
        density_values = np.zeros(len(bins))
        
        for bin_number, bin_val in enumerate(bins):    
            if exp_Sx_per_bin is None:
                exp_Sx = scipy.linalg.expm(bin_val * S)
            else:
                exp_Sx = exp_Sx_per_bin[bin_number]
            if L > 100:
                density_values[bin_number] = self.PhT_density(bin_val, population_number, s1)
            if bin_val < L:
                den_val = 2 * (1 - self.PhT_CDF(bin_val, population_number, s1)) + \
                    (L - bin_val) * self.PhT_density(bin_val, population_number, s1)
                if not np.isreal(den_val) or den_val < -1e-3 :
                    raise Exception('Density is not a positive real :', den_val)
                density_values[bin_number] = prop_connected * float(np.real(den_val).item()) / Z
            else:  # We have reached the end of chromosome
                
                den_cont_at_L = 2 * (1 - self.PhT_CDF(bin_val, population_number, s1)) + \
                (L - bin_val) * self.PhT_density(bin_val, population_number, s1) 
                den_at_delta = - np.dot(np.dot(alpha, exp_Sx), S0_inv)
                density_values[bin_number] = prop_connected * den_cont_at_L / Z
                int_val = integrate.simpson(density_values, x = bins) / prop_connected + den_at_delta / Z
                den_val = den_cont_at_L + den_at_delta
                if not np.isreal(den_val) or den_val < -1e-3:
                    raise Exception('Density is not a positive real :', den_val)
                if not np.isclose(int_val, 1, atol = 1e-4):
                    raise Exception('Density integral is not one : ', int_val, '. Bingrid might be too coarse.')
                density_admixed_at_2 = float(np.real(den_val).item())
                density_values[bin_number] = prop_connected * density_admixed_at_2 / Z + prop_isolated
                
                return bins[bin_start_index:], density_values[bin_start_index:], ETL
        return None

    @abstractmethod
    def PhT_CDF(self, x: float, population_number: int, s1: float | None = None) -> npt.ArrayLike:
        pass

    @abstractmethod
    def PhT_CDF_windowed(self, S: npt.ArrayLike, alpha: npt.ArrayLike, S0_inv: npt.ArrayLike, 
                        bins: npt.ArrayLike, L: float, s1: float | None, pop_number: int,
                        exp_Sx_per_bin: npt.ArrayLike = None) -> npt.ArrayLike:
        pass

    @staticmethod
    def initialize_CDF_values(bins: npt.ArrayLike, S0_inv: npt.ArrayLike, alpha: npt.ArrayLike, L: float):
        r"""
        Initialize the CDF values for the phase-type distribution. Performs initial checks, truncates the bins to the finite chromosome length, and computes the expected tract length under the finite chromosome model.

        Parameters
        ----------
        bins: npt.ArrayLike
            A point grid on :math:`(0, \infty)` where the CDF have to be evaluated.
        S0_inv: npt.ArrayLike
            The sum across columns of the inverse of the transition matrix for the Phase-Type distribution.
        alpha: npt.ArrayLike
            The initial probability vector for the Phase-Type distribution.
        L: float
            The length of the chromosome.

        Returns
        -------
        npt.ArrayLike
            The sorted and truncated bins on :math:`(0, L)` where the CDF will be evaluated.
        npt.ArrayLike
            The initialized CDF values.
        npt.ArrayLike
            The updated `S0_inv`.
        float
            The expected tract length under the infinite chromosome model.
        float
            The expected tract length under the finite chromosome model.
        float
            The normalization factor for the CDF under the finite chromosome model.
        """

        CDF_values = np.zeros(len(bins))
        bins = np.sort(bins)
        S0_inv = np.asarray(S0_inv).ravel()

        ET = -np.dot(alpha, S0_inv)
        Z = ET + L  # Normalization factor
        ETL = L * ET / Z
        return bins, CDF_values, S0_inv, ET, ETL, Z

    def populate_CDF_values(self, bins: npt.ArrayLike, CDF_values: npt.ArrayLike, prop_isolated: float, 
                            prop_connected: float, exp_Sx_per_bin: npt.ArrayLike,
                            S: npt.ArrayLike, alpha: npt.ArrayLike, S0_inv: npt.ArrayLike, L: float, 
                            ET: float, ETL: float, Z: float):
        r"""
        Computes the CDF values for the Phase-type distribution under the finite chromosome model.

        Parameters
        ----------
        bins: npt.ArrayLike
            A point grid on :math:`(0, L)` where the CDF have to be evaluated.
        CDF_values: npt.ArrayLike
            The initialized CDF values.
        prop_isolated: float
            The probability of being in an isolated state.
        prop_connected: float
            The probability of being in a connected state.
        exp_Sx_per_bin: npt.ArrayLike
            The matrix exponential of :math:`\mathbf{S}` times the bin values.
        S: npt.ArrayLike
            The transition matrix for the Phase-Type distribution.
        alpha: npt.ArrayLike
            The initial probability vector for the Phase-Type distribution.
        S0_inv: npt.ArrayLike
            The sum across columns of the inverse of the transition matrix :math:`\mathbf{S}` for the Phase-Type distribution.
        L: float
            The length of the chromosome.
        ET: float
            The expected tract length under the infinite chromosome model.
        ETL: float
            The expected tract length under the finite chromosome model.
        Z: float
            The normalization factor for the CDF under the finite chromosome model.

        Returns
        -------
        npt.ArrayLike
            The computed CDF values.
        float
            The expected tract length under the infinite chromosome model.
        float
            The normalization factor for the CDF under the finite chromosome model.
        float
            The expected tract length under the finite chromosome model.
        """
        
        if not np.isclose(prop_isolated + prop_connected, 1):
            raise Exception('Probabilities of hyper-initial states do not sum up to one.')
        for bin_number, bin_val in enumerate(bins):
            if exp_Sx_per_bin is None:
                exp_Sx = scipy.linalg.expm(bin_val * S)
            else:
                exp_Sx = exp_Sx_per_bin[bin_number]
            if bin_val < L:
                with warnings.catch_warnings():
                    warnings.filterwarnings("ignore", category=ComplexWarning)
                    CDF_values[bin_number] = prop_connected * np.real((self.inner_CDF(bin_val, L, S, exp_Sx, alpha, S0_inv) +
                                                            self.outer_CDF(bin_val, L, S, exp_Sx, alpha, S0_inv))) / Z
            else:
                CDF_values[bin_number:] = 1
                ETL = prop_connected * ETL + prop_isolated * L
                return CDF_values, ET, Z, ETL
        ETL = prop_connected * ETL + prop_isolated * L
        return CDF_values, ET, Z, ETL

    def tractlength_histogram(self, population_number: int, bins: npt.ArrayLike, density: bool=False) -> npt.ArrayLike:
        r"""
        Computes the tract length histogram or density on a point grid
        using a :class:`PhaseTypeDistribution` object. This function considers an infinite chromosome.

        Parameters
        ----------
        population_number : int
            The population of interest whose tract length distribution has to be computed.
            An integer from 0 to the number of populations - 1, corresponding to the column of the migration matrix.
        bins: npt.ArrayLike
            A point grid on :math:`(0, \infty)` where the CDF or density have to be evaluated.
        density : bool, default False
            If True, computes the Phase-type density. Else, returns the histogram values on the grid.

        Returns
        -------
        npt.ArrayLike
            If `density` is True, the density evaluated on bins. Otherwise, the histogram values
            on every interval defined by bins.

        """
        if density:
            density_values = np.zeros(len(bins))
            for bin_number, bin_val in enumerate(bins):
                density_values[bin_number] = self.PhT_density(bin_val, population_number)
            if not np.all(np.isreal(density_values)):
                print(f'Density is complex.\n{density_values}')
            return density_values
        CDF_values = np.zeros(len(bins) + 1)
        for bin_number, bin_val in enumerate(bins):
            CDF_values[bin_number] = self.PhT_CDF(bin_val, population_number)
        CDF_values[-1] = CDF_values[-2]
        if not np.all(np.isreal(CDF_values)):
            print(f'CDF is complex.\n{CDF_values}')
        return np.diff(CDF_values)

    @abstractmethod
    def tractlength_histogram_windowed(self, population_number: int, bins: npt.ArrayLike, L: float,
                                       density=False, freq=False,
                                       exp_Sx_per_bin: npt.ArrayLike = None, exp_Sx_per_bin_f: npt.ArrayLike = None,
                                       exp_Sx_per_bin_m: npt.ArrayLike = None,
                                       return_only=None, hybrid_ped=False) -> npt.ArrayLike:
        pass

    @abstractmethod
    def tract_length_histogram_multi_windowed(self, population_number: int, bins: npt.ArrayLike,
                                              chrom_lengths: npt.ArrayLike) -> npt.ArrayLike:
        pass

    def normalization_factor(self, L: float, S: npt.ArrayLike, 
                            S0_inv: npt.ArrayLike=None, alpha: npt.ArrayLike=None,
                            exp_SL: npt.ArrayLike=None):
        r"""
        Computes the normalization factor :math:`Z` for the density under the finite chromosome model,
        using the CDF evaluated at :math:`L`. This function is coded for testing purposes, as the
        normalization factor can be analitically computed.

        Parameters
        ----------
        L: float
            The chromosome length.
        S: npt.ArrayLike
            The transition matrix for the Phase-Type distribution.
        S0_inv: npt.ArrayLike, default None
            The sum across columns of the inverse of the transition matrix :math:`\mathbf{S}` for the Phase-Type distribution. If None, it will be computed.
        alpha: npt.ArrayLike, default None
            The initial probability vector for the Phase-Type distribution. If None, it will be set to the uniform distribution. 
        exp_SL: npt.ArrayLike, default None
            The value of :math:`e^{\mathbf{S}L}`. If None, it will be computed.
        
        Returns
        -------
        float
            The normalization factor :math:`Z` for the density under the finite chromosome model, computed as CDF(:math:`L`).
        """
        if S0_inv is None:
            S0_inv = np.linalg.inv(S).sum(1)
        if alpha is None:
            alpha = np.ones(len(S0_inv)) / S0_inv
        if exp_SL is None:
            exp_SL = scipy.linalg.expm(L * S)
        return (self.inner_CDF(x=L, 
                            L=L, 
                            S=S,
                            alpha=alpha,
                            S0_inv=S0_inv,
                            exp_Sx=exp_SL) +
                self.outer_CDF(x=L,
                            L=L,
                            S=S, 
                            exp_Sx=exp_SL,
                            alpha=alpha,
                            S0_inv=S0_inv) +
                self.full_CDF(L=L,
                            S=S,
                            exp_SL=exp_SL,
                            alpha=alpha,
                            S0_inv=S0_inv))

    def inner_CDF(self, x: float, L: float, S: npt.ArrayLike,
                exp_Sx: npt.ArrayLike=None, alpha: npt.ArrayLike=None,
                S0_inv: npt.ArrayLike=None):
        r""" 
        Calculates the CDF of tract lengths fully contained within the chromosome of length :math:`L`.

        Parameters
        ----------
        x: float
            The tract length at which the CDF is evaluated.
        S: npt.ArrayLike
            The transition submatrix of the Phase-type distribution.
        L: float
            The chromosome length.
        exp_Sx: npt.ArrayLike, default None
            The value of :math:`e^{\mathbf{S}x}`. If None, it will be computed.
        alpha: npt.ArrayLike, default None
            The initial probability vector for the Phase-type distribution. If None, it will be set to the uniform distribution.
        S0_inv: npt.ArrayLike, default None
            The sum across columns of the inverse of the transition matrix :math:`\mathbf{S}` for the Phase-Type distribution. If None, it will be computed.
            
        Returns
        -------
        float
            The CDF of tract lengths fully contained within the chromosome of length :math:`L`, evaluated at :math:`x`.
        """
        if x > L:
            raise Exception('Cannot find tracts of length greater than L in a window L.')
        if exp_Sx is None:
            exp_Sx = scipy.linalg.expm(x * S)
        if alpha is None:
            alpha = np.ones(len(S)) / len(S)
        if S0_inv is None:
            S0_inv = np.linalg.inv(S).sum(1)
        n_states = len(alpha)
        inner_val = -np.dot(alpha, np.dot((exp_Sx - np.identity(n_states)), L + S0_inv) - np.sum(x * exp_Sx, 1))
        if not np.all(np.isreal(inner_val)) or np.any(inner_val < -1e-3) :
            raise Exception('Inner CDF is not real and positive : ', inner_val)
        return np.real(inner_val)

    def outer_CDF(self, x: float, L: float, S: npt.ArrayLike,
                exp_Sx: npt.ArrayLike=None, alpha: npt.ArrayLike=None,
                S0_inv: npt.ArrayLike=None):
        r"""
        Calculates the length distribution of tract lengths hitting a single chromosome edge. 
            
        Parameters
        ----------
        x: float
            The tract length at which the CDF is evaluated.
        S: npt.ArrayLike
            The transition submatrix for the Phase-type distribution.
        L: float
            The chromosome length.
        exp_Sx: npt.ArrayLike, default None
            The value of :math:`e^{\mathbf{S}x}`. If None, it will be computed.
        alpha: npt.ArrayLike, default None
            The initial probability vector for the Phase-type distribution. If None, it will be set to the uniform distribution.
        S0_inv: npt.ArrayLike, default None
            The sum across columns of the inverse of the transition matrix :math:`\mathbf{S}` for the Phase-type distribution. If None, it will be computed.
            
        Returns
        -------
        float
            The CDF of tract lengths hitting a single chromosome edge, evaluated at :math:`x`.
        """
        if x > L:
            raise Exception('Cannot find tracts of length greater than L in a window L')
        if exp_Sx is None:
            exp_Sx = scipy.linalg.expm(x * S)
        if alpha is None:
            alpha = np.ones(len(S)) / len(S)
        if S0_inv is None:
            S0_inv = np.linalg.inv(S).sum(1)
        n_states = len(alpha)
        outer_val = 2 * np.dot(alpha, np.dot(exp_Sx - np.identity(n_states), S0_inv))
        if not np.all(np.isreal(outer_val)) or np.any(outer_val < -1e-3):
            raise Exception('Outer CDF is not real and positive : ', outer_val)
        return np.real(outer_val)

    def full_CDF(self, L: float, S: npt.ArrayLike,
                exp_SL: npt.ArrayLike=None, alpha: npt.ArrayLike=None,
                S0_inv: npt.ArrayLike=None):
        r""" 
        Computes the length distribution of tract lengths spanning the whole chromosome of length :math:`L`.
        
        Parameters
        ----------
        x: float
            The tract length at which the CDF is evaluated.
        S: npt.ArrayLike
            The transition submatrix for the Phase-type distribution.
        L: float
            The chromosome length.
        exp_SL: npt.ArrayLike, default None
            The value of :math:`e^{\mathbf{S}L}`. If None, it will be computed.
        alpha: npt.ArrayLike, default None
            The initial probability vector for the Phase-type distribution. If None, it will be set to the uniform distribution.
        S0_inv: npt.ArrayLike, default None
            The sum across columns of the inverse of the transition matrix :math:`\mathbf{S}` for the Phase-type distribution. If None, it will be computed.

        Returns
        -------
        float
            The CDF of tract lengths spanning the whole chromosome of length :math:`L`, evaluated at :math:`x`.      
        """
        if exp_SL is None:
            exp_SL = scipy.linalg.expm(L * S)
        if alpha is None:
            alpha = np.ones(len(S)) / len(S)
        if S0_inv is None:
            S0_inv = np.linalg.inv(S).sum(1)
        full_val = -np.dot(alpha, np.dot(exp_SL, S0_inv))
        if not np.all(np.isreal(full_val)) or np.any(full_val < -1e-3) :
            raise Exception('full_CDF is not positive and real : ', full_val)
        return np.real(full_val)

    def loglik(self, bins: np.ndarray, Ls: np.ndarray, 
               data: list[list[int]], num_samples: int, cutoff: int=0):
        r""" 
        Calculates the log-likelihood in a Poisson Random Field. This function is used to fit model parameters.
        
        Parameters
        ----------
        bins: npt.ArrayLike
            A point grid on :math:`(0, L)` where the histogram values have to be evaluated.
        Ls: npt.ArrayLike
            A vector of chromosome lengths for every chromosome considered in the data.
        data: list of list of int
            A list of length equal to the number of populations, where the entry at index :math:`i` is a list of the observed tract counts in every bin for population :math:`i`.
        num_samples: int
            The number of haploid genomes in the sample. Used to scale the predicted tract counts, as the Phase-type distribution is defined for a single haploid genome. If `num_samples` is zero, the log-likelihood is set to zero, as the data does not contain any information.
        cutoff: int, default 0
            The index of the first bin to consider in the likelihood calculation. Used to ignore very short tracts, which are very likely to be false positives in real data. 
        
        Returns
        -------
        float
            The log-likelihood of the data given the model parameters, assuming a Poisson Random Field model.
        """
        
        if num_samples == 0:
            return 0
       
        predicted_tractlength_histogram = None
        ll = 0

        for pop in range(self.num_populations):
            predicted_tractlength_histogram=self.tract_length_histogram_multi_windowed(population_number=pop,
                                                                                    bins=bins,
                                                                                    chrom_lengths=Ls)

            # Replace zeros with machine epsilon to avoid -Inf logarithms
            predicted_tractlength_histogram[predicted_tractlength_histogram <= 0] = np.finfo(float).eps

            ll += sum(-num_samples * predicted_tracts + data_tracts * np.log(num_samples * predicted_tracts) - gammaln(
            data_tracts + 1.)
                   for data_tracts, predicted_tracts in itertools.islice(
            zip(data[pop], predicted_tractlength_histogram),
            cutoff, len(predicted_tractlength_histogram))
                   )           
        
        return ll
    