from __future__ import annotations
from pathlib import Path
from shutil import copy2
from typing import Iterable
import tracts


def prepare_example_outputs_for_docs(
    output_dir_name: str,
    image_patterns: Iterable[str] = ("*.png",),
    table_suffix: str = "_optimal_parameters.txt",
) -> dict[str, Path]:
    """
    Copy example outputs into the matching Sphinx-Gallery output directory.

    This helper is designed for documentation examples executed by
    Sphinx-Gallery. It assumes the current working directory is the example
    directory (e.g. ``example/3pops_sexbiased/ASW``), which is the usual
    Sphinx-Gallery behavior.

    Parameters
    ----------
    output_dir_name: str
        Name of the local output directory generated by the example, e.g.
        ``"output_one_pulse"``.
    image_patterns: Iterable[str]
        File patterns for images to copy.
    table_suffix: str
        Suffix used to identify the optimal-parameters text file.

    Returns
    -------
    dict[str, Path]
        Dictionary containing:
        - ``"destination_dir"``
        - ``"table_file"`` if found
    """
    # Under Sphinx-Gallery, examples are typically executed from their own folder
    example_dir = Path.cwd().resolve()
    gallery_subdir = example_dir.name

    # tracts.__file__ -> /.../tracts/tracts/__init__.py
    # parents[1] -> /.../tracts  (project root)
    project_root = Path(tracts.__file__).resolve().parents[1]

    src_out = example_dir / output_dir_name
    dst_out = (
        project_root
        / "docs"
        / "source"
        / "auto_examples"
        / gallery_subdir
        / output_dir_name
    )

    if not src_out.exists():
        raise FileNotFoundError(f"Source output directory does not exist: {src_out}")

    dst_out.mkdir(parents=True, exist_ok=True)

    # Copy image files
    for pattern in image_patterns:
        for f in src_out.glob(pattern):
            if f.is_file():
                copy2(f, dst_out / f.name)

    result: dict[str, Path] = {"destination_dir": dst_out}

    # Copy the optimal-parameters table file
    table_candidates = sorted(src_out.glob(f"*{table_suffix}"))
    if table_candidates:
        table_file = table_candidates[0]
        copied_table = dst_out / table_file.name
        copy2(table_file, copied_table)
        result["table_file"] = copied_table

    return result